### ISSUE TITLE
[Documentation]: Not clear.

### ISSUE THREAD

**Issue by NitkarshChourasia** [PBJI/ultimate-tic-tac-toe-2#12]
- Programs are not well documented.
- README.md is not precise, a reader might be confused as what features are pending, and what is to added.
That is the current state, and the state which we want.
Improve this.
- Make it clear, understandable and precise.
- Can't work unless, well documented.
- Also, make a license for this repo.
- Make a contributing.md.
- Also, add images, explaining different things.
- Also, how to install and uninstall, and run the program.

This, is a repo, which is does not count to open source standards.

**Comment by PBJI** [comment]
Hi @NitkarshChourasia, it is glad that you pointed out these suggestions and even pulled a request fulfilling some of the suggested changes by your own self on #14 . I am new to the world of open source and having hard time setting myself upto the standards, but don't worry I'll try my best to inculcate some of the above practices in my daily workflows.

**Comment by NitkarshChourasia** [comment]
Okay.
