### ISSUE TITLE
branch_issue: default branch of yours?

### ISSUE THREAD

**Issue by NitkarshChourasia** [PBJI/ultimate-tic-tac-toe-2#15]
Check whether the default branch of yours is what you expected it to be.
module is the current default branch.
I think you intended bot to be your default branch?!

**Comment by PBJI** [comment]
The default branch is modules. This branch will house all the individual feature combined from 3 completely indepedent branches which are bot, backend and frontend. Hence the name **modules**

**Comment by PBJI** [comment]
The expected goals for this branches are written in README.md, with time we can carefully specify the goals clearly with more research and development.

**Comment by NitkarshChourasia** [comment]
> The expected goals for this branches are written in README.md, with time we can carefully specify the goals clearly with more research and development.

Okay.
